stages:
  data_collection:
    cmd: python src/data_collection.py
    deps:
    - src/data_collection.py
    params:
    - data_collection.test_size
    outs:
    - data/raw
  data_processing:
    cmd: python src/data_prep.py
    deps:
    - data\raw
    - src\data_prep.py
    outs:
    - data/propcessed
