stages:
  data_collection:
    cmd: python src/data_collection.py
    deps:
    - src/data_collection.py
    params:
    - data_collection.test_size
    outs:
    - data/raw
  data_processing:
    cmd: python src/data_prep.py
    deps:
    - data\raw
    - src\data_prep.py
    outs:
    - data\processed
  model_buuilding:
    cmd: python src/model_building.py
    deps:
    - data/processed
    - src/model_building.py
    outs:
    - model.pkl
  model_evaluation:
    cmd: python src/model_eval.py
    deps:
    - model.pkl
    - src/model_eval.py
    metrics:
    - metrics.json
